Added a todo list with vue
Computerization/New-member-practice-commit pull request #22
Opened 2020-01-14 10:48 UTC by Josh-Cena

An overdue project of a todo list

2020-01-15 16:31 UTC, yechs requested changes
Stylistic:
1. Use spaces instead of tabs
2. Avoid spaces in file names, use underscores (_) to replace spaces, or alternatively use camel cases (e.g. TodolistWithVue)

Functional:
@madaomax

2020-01-16 15:27 UTC, madaomax commented on Joshua-Todolist with vue/Todolist with vue.html
> +	<script src="vue.js"></script>
should be: src="Todolist with vue.js"

2020-01-17 01:41 UTC, Josh-Cena commented on Joshua-Todolist with vue/Todolist with vue.html
> +	<script src="vue.js"></script>
这是按照vuejs.org上的教程写法来的，在head中引用vue.js，再在body中引用与网页相关的js文件

2020-01-17 05:56 UTC, yechs commented on Joshua-Todolist with vue/Todolist with vue.html
> +	<script src="vue.js"></script>
这里是没错的hhh
不过最好是把这里的 "vue.js" 替换成一些第三方网站（比如CDN）的链接

至于为什么这么做没错，以下是原因：

head 中引入的 script (vue.js) 会在浏览器渲染 DOM 【之前】加载并在被调用时运行
body 中引入的 script (Todolist with vue.js) 会在浏览器渲染 DOM 【之后】加载并运行

正因为这样，国际惯例是把 jQuery 或者 vue 一类的库放在 head 里面加载（避免运行【依赖于这个库的 script】时，库没有加载）
至于那些会对DOM进行操作的，是【必须】要放在 body 结尾的，避免运行 script 时，要操作的那个 DOM element 没有加载

2020-01-29 10:12 UTC, Josh-Cena commented
已完成更改：
缩进使用两个空格；文件名中使用下划线
尚未更改Vue源文件引用方式

2020-01-30 05:25 UTC, yechs commented on Joshua-Todolist with vue/Todolist_with_vue.html
> +  <script src="Todolist with vue.js"></script>
稍等，文件名改了之后这里是不是也要改一下

2020-01-30 10:54 UTC, Josh-Cena commented on Joshua-Todolist with vue/Todolist_with_vue.html
> +  <script src="Todolist with vue.js"></script>
小失误hhh

2020-01-30 10:55 UTC, Josh-Cena commented
Publish branch之后还能不能添加文件？

2020-01-30 16:02 UTC, yechs commented
> 
> Publish branch之后还能不能添加文件？

可以的；
commit & push 就可以了

2020-09-16 12:09 UTC, merged